# Generated by Django 5.1.15 on 2026-07-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.CharField(default="RevisorPlus Premium", max_length=50),
        ),
    ]
