# Generated by Django 5.1.15 on 2026-07-26 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0004_alter_question_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=160, unique=True)),
                ("area", models.CharField(blank=True, max_length=100)),
                ("admissions_body", models.CharField(blank=True, max_length=150)),
                ("test_window", models.CharField(blank=True, max_length=80)),
                (
                    "requirement_note",
                    models.TextField(
                        blank=True,
                        help_text="How selection works, in words. Never state a pass mark unless it is officially published — and record the source below if it is.",
                    ),
                ),
                ("source_url", models.URLField(blank=True)),
                (
                    "source_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("verified", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                (
                    "papers",
                    models.ManyToManyField(
                        blank=True, related_name="schools", to="catalog.section"
                    ),
                ),
            ],
            options={
                "ordering": ["area", "name"],
            },
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_note", models.CharField(blank=True, max_length=200)),
                ("exam_date", models.DateField()),
                ("target_overall", models.PositiveSmallIntegerField(default=80)),
                ("target_hours", models.PositiveSmallIntegerField(default=60)),
                ("weekly_hours_available", models.FloatField(default=3.0)),
                (
                    "set_by",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("parent", "Parent"),
                            ("tutor", "Tutor"),
                        ],
                        default="student",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goals",
                        to="goals.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SectionTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_accuracy", models.PositiveSmallIntegerField(default=80)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_targets",
                        to="goals.goal",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.section",
                    ),
                ),
            ],
            options={
                "ordering": ["section__order"],
                "unique_together": {("goal", "section")},
            },
        ),
    ]
