# Generated by Django 5.1.15 on 2026-10-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='exam_format',
            field=models.CharField(blank=True, choices=[('gl', 'GL Assessment'), ('set', 'Sutton SET'), ('bespoke', "Bespoke (the school's own test)")], max_length=10),
        ),
    ]
