# Generated by Django 5.1.15 on 2026-10-07 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WordPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('mixed', 'Mixed'), ('synonym', 'Synonym match'), ('odd_one_out', 'Odd one out'), ('gap', 'Fill the gap')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('xp_awarded', models.PositiveIntegerField(default=0)),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_rounds', to=settings.AUTH_USER_MODEL)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rounds', to='vocab.wordpack')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='VocabProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('best_streak', models.PositiveIntegerField(default=0)),
                ('last_played_on', models.DateField(blank=True, null=True)),
                ('pupil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headword', models.CharField(max_length=40, unique=True)),
                ('pos', models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb')], max_length=10)),
                ('year', models.PositiveSmallIntegerField()),
                ('definition', models.TextField()),
                ('synonyms', models.JSONField(default=list)),
                ('group', models.SlugField(max_length=60)),
                ('example', models.TextField()),
                ('gap_frame', models.TextField()),
                ('gap_distractors', models.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('packs', models.ManyToManyField(blank=True, related_name='words', to='vocab.wordpack')),
            ],
            options={
                'ordering': ['headword'],
            },
        ),
        migrations.CreateModel(
            name='WordProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.PositiveSmallIntegerField(default=1)),
                ('due_on', models.DateField()),
                ('times_seen', models.PositiveIntegerField(default=0)),
                ('times_correct', models.PositiveIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_progress', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress', to='vocab.word')),
            ],
        ),
        migrations.CreateModel(
            name='RoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(choices=[('synonym', 'Synonym match'), ('odd_one_out', 'Odd one out'), ('gap', 'Fill the gap')], max_length=20)),
                ('options', models.JSONField()),
                ('answer_index', models.PositiveSmallIntegerField()),
                ('chosen_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('correct', models.BooleanField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vocab.round')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='round_items', to='vocab.word')),
            ],
            options={
                'ordering': ['round', 'position'],
                'constraints': [models.UniqueConstraint(fields=('round', 'position'), name='vocab_item_position_once')],
            },
        ),
        migrations.AddIndex(
            model_name='round',
            index=models.Index(fields=['pupil', '-started_at'], name='vocab_round_pupil_i_05b4be_idx'),
        ),
        migrations.AddIndex(
            model_name='wordprogress',
            index=models.Index(fields=['pupil', 'due_on'], name='vocab_wordp_pupil_i_8c3298_idx'),
        ),
        migrations.AddConstraint(
            model_name='wordprogress',
            constraint=models.UniqueConstraint(fields=('pupil', 'word'), name='vocab_progress_once_per_word'),
        ),
    ]
