# Generated by Django 5.1.15 on 2026-09-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_reset_unparented_pupils"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_customer_id",
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
    ]
