# Generated by Django 5.1.15 on 2026-07-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testsession",
            name="deck_state",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
