# Generated by Django 5.1.15 on 2026-07-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0002_testsession_deck_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="attempt",
            name="answer_given",
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name="attempt",
            name="awaiting_marking",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="attempt",
            name="marks_available",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="attempt",
            name="marks_earned",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
