# Generated by Django 5.1.15 on 2026-07-26 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_question_question_subtopic_active_d"),
        ("practice", "0003_attempt_answer_given_attempt_awaiting_marking_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="attempt",
            index=models.Index(
                fields=["student", "subtopic"], name="attempt_student_subtopic"
            ),
        ),
        migrations.AddIndex(
            model_name="attempt",
            index=models.Index(fields=["created_at"], name="attempt_created_at"),
        ),
    ]
