# Generated by Django 5.1.15 on 2026-09-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0004_attempt_attempt_student_subtopic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attempt",
            name="tier",
            field=models.CharField(
                choices=[("free", "Free"), ("premium", "Premium")],
                db_index=True,
                default="free",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="testsession",
            name="mode",
            field=models.CharField(
                choices=[
                    ("practice", "Practice"),
                    ("test", "Timed test"),
                    ("homework", "Homework"),
                    ("mock", "Mock paper"),
                ],
                default="practice",
                max_length=12,
            ),
        ),
    ]
