# Generated by Django 5.1.15 on 2026-07-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="question",
            name="is_placeholder",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="question",
            name="source",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
