# Generated by Django 5.1.15 on 2026-07-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_question_image_question_is_placeholder_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="kind",
            field=models.CharField(
                choices=[("mcq", "Multiple choice")], default="mcq", max_length=10
            ),
        ),
    ]
