# Generated by Django 5.1.15 on 2026-07-26 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_question_kind"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AddField(
            model_name="question",
            name="accepted_alternatives",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="question",
            name="answer_text",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="question",
            name="figure",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="label",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name="question",
            name="marking",
            field=models.CharField(
                choices=[
                    ("auto", "Auto-marked"),
                    ("keyword", "Keyword-matched"),
                    ("rubric", "Rubric — needs a marker"),
                ],
                default="auto",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="marks",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="question",
            name="model_answer",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="question",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parts",
                to="catalog.question",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="reject_keywords",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="question",
            name="rubric",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="tolerance",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="unit",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="question",
            name="working_note",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="kind",
            field=models.CharField(
                choices=[
                    ("mcq", "Multiple choice"),
                    ("numeric", "Numeric entry"),
                    ("short_text", "Short text"),
                    ("extended_text", "Extended writing"),
                ],
                default="mcq",
                max_length=16,
            ),
        ),
    ]
