# Generated by Django 5.1.15 on 2026-07-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_question_options_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["subtopic", "active", "difficulty"],
                name="question_subtopic_active_d",
            ),
        ),
    ]
