# Generated by Django 5.1.15 on 2026-07-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_question_question_subtopic_active_d"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="gen_key",
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
