# Generated by Django 5.1.15 on 2026-07-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_question_gen_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="answeroption",
            name="misconception",
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
