# Generated by Django 5.1.15 on 2026-08-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_answeroption_misconception"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
    ]
