# Generated by Django 5.1.15 on 2026-08-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_question_question_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="also_tests",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="subtopic",
            name="topic",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="subtopic",
            name="topic_order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
