# Generated by Django 5.1.15 on 2026-08-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_question_also_tests_subtopic_topic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="line_ref",
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
