# Generated by Django 5.1.15 on 2026-08-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_question_line_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="answeroption",
            name="label",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="question",
            name="gap_number",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="kind",
            field=models.CharField(
                choices=[
                    ("mcq", "Multiple choice"),
                    ("numeric", "Numeric entry"),
                    ("short_text", "Short text"),
                    ("extended_text", "Extended writing"),
                    ("error_span", "Spot the error"),
                    ("select_word", "Click the word"),
                    ("cloze_gap", "Cloze gap"),
                ],
                default="mcq",
                max_length=16,
            ),
        ),
    ]
