# Generated by Django 5.1.15 on 2026-08-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_answeroption_label_question_gap_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="passage_source",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="question",
            name="passage_title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
