# Generated by Django 5.1.15 on 2026-08-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_question_passage_source_question_passage_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="answeroption",
            name="figure",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
