# Generated by Django 5.1.15 on 2026-08-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_question_passage_source_question_passage_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="answeroption",
            name="group",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="instruction",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="question",
            name="worked_example",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="kind",
            field=models.CharField(
                choices=[
                    ("mcq", "Multiple choice"),
                    ("numeric", "Numeric entry"),
                    ("short_text", "Short text"),
                    ("extended_text", "Extended writing"),
                    ("error_span", "Spot the error"),
                    ("select_word", "Click the word"),
                    ("cloze_gap", "Cloze gap"),
                    ("grouped_options", "One from each bracket"),
                ],
                default="mcq",
                max_length=16,
            ),
        ),
    ]
