# Generated by Django 5.1.15 on 2026-08-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    # Renumbered from 0013 and re-pointed. This was authored in parallel with
    # 0013_answeroption_group_question_instruction_and_more, so both were 0013
    # and both depended on 0012 — two leaf nodes on the same app, which makes
    # `makemigrations --check` fail and needs a merge migration. Renumbering is
    # the cheaper fix while the branch is unmerged: there is nothing to migrate
    # away from yet.
    dependencies = [
        ("catalog", "0013_answeroption_group_question_instruction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answeroption",
            name="figure",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
