# Generated by Django 5.1.15 on 2026-09-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_answeroption_figure"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="ref",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ref", ""), _negated=True),
                fields=("source", "ref"),
                name="question_source_ref_uniq",
            ),
        ),
    ]
