# Generated by Django 5.1.15 on 2026-08-31 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_onboarding', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='school',
            new_name='school_onbo_status_bc7ad4_idx',
            old_name='school_onbo_status_58a8ea_idx',
        ),
        migrations.RenameIndex(
            model_name='school',
            new_name='school_onbo_easting_739000_idx',
            old_name='school_onbo_easting_f84783_idx',
        ),
    ]
